import type { Geom2, Poly3, Slice } from "../../geometries/types";

export interface ExtrudeFromSlicesOptions<Base> {
	numberOfSlices?: number;
	capStart?: boolean;
	capEnd?: boolean;
	close?: boolean;
	repair?: boolean;
	callback?: (progress: number, index: number, base: Base) => Slice;
}

import { Array as JsArray, Object } from "@rbxts/luau-polyfill";

import * as geom2 from "../../geometries/geom2/index";
import * as geom3 from "../../geometries/geom3/index";
import * as poly3 from "../../geometries/poly3/index";
import * as slice from "../../geometries/slice/index";
import * as mat4 from "../../maths/mat4/index";
import { extrudeWalls } from "./extrudeWalls";

const defaultCallback = <Base>(progress: number, index: number, base: Base) => {
	let baseSlice: Slice = undefined!;
	if (geom2.isA(base as Geom2)) baseSlice = slice.fromGeom2(base as Geom2);
	if (poly3.isA(base as Poly3)) baseSlice = slice.fromVertices(poly3.toVertices(base as Poly3));

	return progress === 0 || progress === 1
		? slice.transform(mat4.fromTranslation(mat4.create(), [0, 0, progress]), baseSlice)
		: undefined;
};

/**
 * Extrude a solid from the slices as returned by the callback function.
 * @see slice
 *
 * @param {object} options - options for extrude
 * @param {number} [options.numberOfSlices=2] the number of slices to be generated by the callback
 * @param {boolean} [options.capStart=true] the solid should have a cap at the start
 * @param {boolean} [options.capEnd=true] the solid should have a cap at the end
 * @param {boolean} [options.close=false] the solid should have a closing section between start and end
 * @param {boolean} [options.repair=true] - repair gaps in the geometry
 * @param {Function} [options.callback] the callback function that generates each slice
 * @param {object} base - the base object which is used to create slices (see the example for callback information)
 * @return {Geom3} the extruded shape
 * @alias module:modeling/extrusions.extrudeFromSlices
 *
 * @example
 * // Parameters:
 * //   progress : the percent complete [0..1]
 * //   index : the index of the current slice [0..numberOfSlices - 1]
 * //   base : the base object as given
 * // Return Value:
 * //   slice or null (to skip)
 * const callback = (progress, index, base) => {
 *   ...
 *   return slice
 * }
 */
export const extrudeFromSlices = <Base>(options: ExtrudeFromSlicesOptions<Base>, base: Base) => {
	const defaults = {
		numberOfSlices: 2,
		capStart: true,
		capEnd: true,
		close: false,
		callback: defaultCallback,
	};
	const { numberOfSlices, capStart, capEnd, close, callback: generate } = Object.assign({}, defaults, options);

	if (numberOfSlices < 2) throw "numberOfSlices must be 2 or more";

	const sMax = numberOfSlices - 1;

	let startSlice: Slice = undefined!;
	let endSlice: Slice = undefined!;
	let prevSlice: Slice = undefined!;
	let polygons: Poly3[] = [];
	for (let s = 0; s < numberOfSlices; s++) {
		// invoke the callback function to get the next slice
		// NOTE: callback can return null to skip the slice
		const currentSlice = generate(s / sMax, s, base);

		if (currentSlice) {
			if (!slice.isA(currentSlice)) throw "the callback function must return slice objects";

			if (currentSlice.contours.size() === 0)
				throw "the callback function must return slices with one or more contours";

			if (prevSlice) {
				//polygons = polygons.concat(extrudeWalls(prevSlice, currentSlice));
				polygons = JsArray.concat(polygons, extrudeWalls(prevSlice, currentSlice));
			}

			// save start and end slices for caps if necessary
			if (s === 0) startSlice = currentSlice;
			if (s === numberOfSlices - 1) endSlice = currentSlice;

			prevSlice = currentSlice;
		}
	}

	if (capEnd) {
		// create a cap at the end
		const endPolygons = slice.toPolygons(endSlice);
		//polygons = polygons.concat(endPolygons);
		polygons = JsArray.concat(polygons, endPolygons);
	}
	if (capStart) {
		// create a cap at the start
		const startPolygons = slice.toPolygons(startSlice).map(poly3.invert);
		//polygons = polygons.concat(startPolygons);
		polygons = JsArray.concat(polygons, startPolygons);
	}
	if (!capStart && !capEnd) {
		// create walls between end and start slices
		if (close && !slice.equals(endSlice, startSlice)) {
			//polygons = polygons.concat(extrudeWalls(endSlice, startSlice));
			polygons = JsArray.concat(polygons, extrudeWalls(endSlice, startSlice));
		}
	}
	return geom3.create(polygons);
};
